spring.application.name=appfinanceiro-api
api.security.token.secret=/vatCA/lOch5j311K5NzxZ/+kmYcf5Mo/U4zTVxHj83MeUZVRJ//Q/Lr8W0JSQE1OW9ZaLCfx8W15Tm3yYfGBQ==

spring.datasource.url=jdbc:postgresql://localhost:5432/controlefinanceiro-api
spring.datasource.username=postgres
spring.datasource.password=sua senha

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Configuração de E-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu email
spring.mail.password=sua senha
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true